In [6]:
import pandas as pd
import matplotlib.pyplot as plt

# Step 1: Read the data from the Excel file
df = pd.read_excel("pokemon_data.xlsx")

# Get all Pokemons whose spawn rate is less than 5%
spawn_rate_less_than_5 = df[df["spawn_chance"] < 5]
print("Pokemons with spawn rate less than 5%:")
print(spawn_rate_less_than_5[["name", "spawn_chance"]])

# Get all Pokemons that have less than 4 weaknesses
less_than_4_weaknesses = df[df["weaknesses"].str.len() < 4]
print("Pokemons with less than 4 weaknesses:")
print(less_than_4_weaknesses[["name", "weaknesses"]])

# Get all Pokemons that have no multipliers at all
no_multipliers = df[df["spawn_time"].isnull()]
print("Pokemons with no multipliers:")
print(no_multipliers["name"])

# Get all Pokemons that do not have more than 2 evolutions
less_than_2_evolutions = df[df["next_evolution"].notnull() & df["next_evolution"].str.contains(",")]
print("Pokemons with less than 2 evolutions:")
print(less_than_2_evolutions[["name", "next_evolution"]])

# Get all Pokemons whose spawn time is less than 300 seconds
def convert_spawn_time(spawn_time):
    minutes, seconds = map(int, spawn_time.split(":"))
    return minutes * 60 + seconds

df["spawn_time_seconds"] = df["spawn_time"].apply(convert_spawn_time)
spawn_time_less_than_300 = df[df["spawn_time_seconds"] < 300]
print("Pokemons with spawn time less than 300 seconds:")
print(spawn_time_less_than_300[["name", "spawn_time"]])

# Get all Pokemon who have more than two types of capabilities
more_than_2_types = df[df["type"].str.count(",") > 1]
print("Pokemons with more than two types of capabilities:")
print(more_than_2_types[["name", "type"]])

# Step 2: Plotting for better visualizations

# Bar plot for spawn rate analysis
plt.figure(figsize=(10, 6))
plt.bar(spawn_rate_less_than_5["name"], spawn_rate_less_than_5["spawn_chance"])
plt.xticks(rotation=90)
plt.xlabel("Pokemon")
plt.ylabel("Spawn Rate (%)")
plt.title("Pokemons with Spawn Rate Less than 5%")
plt.tight_layout()
plt.show()

# Bar plot for weakness analysis
weakness_counts = df["weaknesses"].str.len().value_counts().sort_index()
plt.figure(figsize=(8, 6))
plt.bar(weakness_counts.index, weakness_counts.values)
plt.xlabel("Number of Weaknesses")
plt.ylabel("Count")
plt.title("Distribution of Number of Weaknesses")
plt.tight_layout()
plt.show()

# Pie chart for Pokemon types analysis
type_counts = df["type"].str.count(",") + 1
type_counts = type_counts.value_counts().sort_index()
plt.figure(figsize=(8, 6))
plt.pie(type_counts.values, labels=type_counts.index, autopct='%1.1f%%', startangle=90)
plt.axis('equal')
plt.title("Distribution of Pokemon Types")
plt.tight_layout()
plt.show()

Pokemons with spawn rate less than 5%:
           name  spawn_chance
0     Bulbasaur        0.6900
1       Ivysaur        0.0420
2      Venusaur        0.0170
3    Charmander        0.2530
4    Charmeleon        0.0120
..          ...           ...
146     Dratini        0.3000
147   Dragonair        0.0200
148   Dragonite        0.0011
149      Mewtwo        0.0000
150         Mew        0.0000

[147 rows x 2 columns]
Pokemons with less than 4 weaknesses:
Empty DataFrame
Columns: [name, weaknesses]
Index: []
Pokemons with no multipliers:
131       Ditto
143    Articuno
144      Zapdos
145     Moltres
149      Mewtwo
150         Mew
Name: name, dtype: object
Pokemons with less than 2 evolutions:
                   name              next_evolution
0             Bulbasaur           Ivysaur, Venusaur
3            Charmander       Charmeleon, Charizard
6              Squirtle        Wartortle, Blastoise
9              Caterpie         Metapod, Butterfree
12               Weedle            Kakuna, Beedrill
15               Pidgey          Pidgeotto, Pidgeot
28   Nidoran ♀ (Female)         Nidorina, Nidoqueen
31     Nidoran ♂ (Male)          Nidorino, Nidoking
42               Oddish            Gloom, Vileplume
59              Poliwag        Poliwhirl, Poliwrath
62                 Abra           Kadabra, Alakazam
65               Machop            Machoke, Machamp
68           Bellsprout      Weepinbell, Victreebel
73              Geodude             Graveler, Golem
91               Gastly             Haunter, Gengar
132               Eevee  Vaporeon, Jolteon, Flareon
146             Dratini        Dragonair, Dragonite

AttributeError: 'float' object has no attribute 'split'

In [5]:
import pandas as pd

# Step 1: Read the data from the Excel file
df = pd.read_excel("pokemon_data.xlsx")

# Print column names
print(df.columns)

Index(['id', 'num', 'name', 'img', 'type', 'height', 'weight', 'candy',
       'candy_count', 'egg', 'spawn_chance', 'avg_spawns', 'spawn_time',
       'weaknesses', 'next_evolution', 'prev_evolution'],
      dtype='object')

In [8]:
import pandas as pd
import matplotlib.pyplot as plt

# Step 1: Read the data from the Excel file
df = pd.read_excel("pokemon_data.xlsx")

# Get all Pokemons whose spawn rate is less than 5%
spawn_rate_less_than_5 = df[df["spawn_chance"] < 5]
print("Pokemons with spawn rate less than 5%:")
print(spawn_rate_less_than_5[["name", "spawn_chance"]])

# Get all Pokemons that have less than 4 weaknesses
less_than_4_weaknesses = df[df["weaknesses"].str.len() < 4]
print("Pokemons with less than 4 weaknesses:")
print(less_than_4_weaknesses[["name", "weaknesses"]])

# Get all Pokemons that have no multipliers at all
no_multipliers = df[df["spawn_time"].isnull()]
print("Pokemons with no multipliers:")
print(no_multipliers["name"])

# Get all Pokemons that do not have more than 2 evolutions
less_than_2_evolutions = df[df["next_evolution"].notnull() & df["next_evolution"].str.contains(",")]
print("Pokemons with less than 2 evolutions:")
print(less_than_2_evolutions[["name", "next_evolution"]])

# Get all Pokemons whose spawn time is less than 300 seconds
def convert_spawn_time(spawn_time):
    if isinstance(spawn_time, float):  # Check if the value is float
        spawn_time = str(int(spawn_time))  # Convert float to integer and then to string
    minutes, seconds = map(int, spawn_time.split(":"))
    return minutes * 60 + seconds

df["spawn_time_seconds"] = df["spawn_time"].apply(convert_spawn_time)
spawn_time_less_than_300 = df[df["spawn_time_seconds"] < 300]
print("Pokemons with spawn time less than 300 seconds:")
print(spawn_time_less_than_300[["name", "spawn_time"]])

# Get all Pokemon who have more than two types of capabilities
more_than_2_types = df[df["type"].str.count(",") > 1]
print("Pokemons with more than two types of capabilities:")
print(more_than_2_types[["name", "type"]])

# Step 2: Plotting for better visualizations
# (Same as the previous code snippet)

Pokemons with spawn rate less than 5%:
           name  spawn_chance
0     Bulbasaur        0.6900
1       Ivysaur        0.0420
2      Venusaur        0.0170
3    Charmander        0.2530
4    Charmeleon        0.0120
..          ...           ...
146     Dratini        0.3000
147   Dragonair        0.0200
148   Dragonite        0.0011
149      Mewtwo        0.0000
150         Mew        0.0000

[147 rows x 2 columns]
Pokemons with less than 4 weaknesses:
Empty DataFrame
Columns: [name, weaknesses]
Index: []
Pokemons with no multipliers:
131       Ditto
143    Articuno
144      Zapdos
145     Moltres
149      Mewtwo
150         Mew
Name: name, dtype: object
Pokemons with less than 2 evolutions:
                   name              next_evolution
0             Bulbasaur           Ivysaur, Venusaur
3            Charmander       Charmeleon, Charizard
6              Squirtle        Wartortle, Blastoise
9              Caterpie         Metapod, Butterfree
12               Weedle            Kakuna, Beedrill
15               Pidgey          Pidgeotto, Pidgeot
28   Nidoran ♀ (Female)         Nidorina, Nidoqueen
31     Nidoran ♂ (Male)          Nidorino, Nidoking
42               Oddish            Gloom, Vileplume
59              Poliwag        Poliwhirl, Poliwrath
62                 Abra           Kadabra, Alakazam
65               Machop            Machoke, Machamp
68           Bellsprout      Weepinbell, Victreebel
73              Geodude             Graveler, Golem
91               Gastly             Haunter, Gengar
132               Eevee  Vaporeon, Jolteon, Flareon
146             Dratini        Dragonair, Dragonite

ValueError: cannot convert float NaN to integer

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Read the data from the Excel file
df = pd.read_excel("pokemon_data.xlsx")

# Get all Pokemons whose spawn rate is less than 5%
spawn_rate_less_than_5 = df[df["spawn_chance"] < 5]
print("Pokemons with spawn rate less than 5%:")
print(spawn_rate_less_than_5[["name", "spawn_chance"]])

# Get all Pokemons that have less than 4 weaknesses
less_than_4_weaknesses = df[df["weaknesses"].str.len() < 4]
print("Pokemons with less than 4 weaknesses:")
print(less_than_4_weaknesses[["name", "weaknesses"]])

# Get all Pokemons that have no multipliers at all
no_multipliers = df[df["spawn_time"].isnull()]
print("Pokemons with no multipliers:")
print(no_multipliers["name"])

# Get all Pokemons that do not have more than 2 evolutions
less_than_2_evolutions = df[df["next_evolution"].notnull() & df["next_evolution"].str.contains(",")]
print("Pokemons with less than 2 evolutions:")
print(less_than_2_evolutions[["name", "next_evolution"]])

# Get all Pokemons whose spawn time is less than 300 seconds
def convert_spawn_time(spawn_time):
    if isinstance(spawn_time, float) and np.isnan(spawn_time):  # Check if the value is NaN
        return -1  # Return -1 as a default value for NaN
    if isinstance(spawn_time, float):  # Check if the value is float
        spawn_time = str(int(spawn_time))  # Convert float to integer and then to string
    minutes, seconds = map(int, spawn_time.split(":"))
    return minutes * 60 + seconds

df["spawn_time_seconds"] = df["spawn_time"].apply(convert_spawn_time)
spawn_time_less_than_300 = df[df["spawn_time_seconds"] < 300]
print("Pokemons with spawn time less than 300 seconds:")
print(spawn_time_less_than_300[["name", "spawn_time"]])

# Get all Pokemon who have more than two types of capabilities
more_than_2_types = df[df["type"].str.count(",") > 1]
print("Pokemons with more than two types of capabilities:")
print(more_than_2_types[["name", "type"]])

# Step 2: Plotting for better visualizations
# (Same as the previous code snippet)

Pokemons with spawn rate less than 5%:
           name  spawn_chance
0     Bulbasaur        0.6900
1       Ivysaur        0.0420
2      Venusaur        0.0170
3    Charmander        0.2530
4    Charmeleon        0.0120
..          ...           ...
146     Dratini        0.3000
147   Dragonair        0.0200
148   Dragonite        0.0011
149      Mewtwo        0.0000
150         Mew        0.0000

[147 rows x 2 columns]
Pokemons with less than 4 weaknesses:
Empty DataFrame
Columns: [name, weaknesses]
Index: []
Pokemons with no multipliers:
131       Ditto
143    Articuno
144      Zapdos
145     Moltres
149      Mewtwo
150         Mew
Name: name, dtype: object
Pokemons with less than 2 evolutions:
                   name              next_evolution
0             Bulbasaur           Ivysaur, Venusaur
3            Charmander       Charmeleon, Charizard
6              Squirtle        Wartortle, Blastoise
9              Caterpie         Metapod, Butterfree
12               Weedle            Kakuna, Beedrill
15               Pidgey          Pidgeotto, Pidgeot
28   Nidoran ♀ (Female)         Nidorina, Nidoqueen
31     Nidoran ♂ (Male)          Nidorino, Nidoking
42               Oddish            Gloom, Vileplume
59              Poliwag        Poliwhirl, Poliwrath
62                 Abra           Kadabra, Alakazam
65               Machop            Machoke, Machamp
68           Bellsprout      Weepinbell, Victreebel
73              Geodude             Graveler, Golem
91               Gastly             Haunter, Gengar
132               Eevee  Vaporeon, Jolteon, Flareon
146             Dratini        Dragonair, Dragonite
Pokemons with spawn time less than 300 seconds:
          name spawn_time
6     Squirtle      04:25
8    Blastoise      00:06
10     Metapod      02:11
12      Weedle      02:21
13      Kakuna      02:30
..         ...        ...
143   Articuno        NaN
144     Zapdos        NaN
145    Moltres        NaN
149     Mewtwo        NaN
150        Mew        NaN

[81 rows x 2 columns]
Pokemons with more than two types of capabilities:
Empty DataFrame
Columns: [name, type]
Index: []